name: Kustomize Build Check - Basic

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
    branches:
      - main

jobs:
  validate:
    name: Validate Kustomize Builds
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Required for git diff
      
      - name: Run Kustomize Build Check
        uses: michielvha/kustomize-build-check-action@main
        with:
          enable-helm: true
          fail-on-error: true
          base-ref: ${{ github.event.pull_request.base.sha || 'HEAD~1' }} # great to capture all changes in pull request not just the latest commit, safe fallback to the defaul (latest commit only) when it's not a pull request
