name: Kustomize Check - Custom Base Reference

on:
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  validate:
    name: Validate Against Target Branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Determine base branch
        id: base
        run: |
          # Use the PR base ref
          echo "ref=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
      
      - name: Run Kustomize Build Check
        uses: michielvha/kustomize-build-check-action@main
        with:
          base-ref: ${{ steps.base.outputs.ref }}
          enable-helm: true
          fail-on-error: true
          root-dir: '.'
