name: Kustomize Check - Monorepo

on:
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    name: Detect Changed Projects
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.projects.outputs.matrix }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Detect changed projects
        id: projects
        run: |
          # Get list of changed directories
          CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | \
            grep -E '^projects/[^/]+/' | \
            cut -d/ -f1-2 | \
            sort -u | \
            jq -R -s -c 'split("\n") | map(select(length > 0))')
          
          echo "matrix=$CHANGED" >> $GITHUB_OUTPUT
  
  validate:
    name: Validate ${{ matrix.project }}
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.projects != '[]'
    
    strategy:
      matrix:
        project: ${{ fromJson(needs.detect-changes.outputs.projects) }}
      fail-fast: false
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Validate ${{ matrix.project }}
        uses: michielvha/kustomize-build-check@v1
        with:
          root-dir: ${{ matrix.project }}
          enable-helm: true
          fail-on-error: true
